Drop requirement on boost by using C++17
gsauthof/pe-util pull request #15
Opened 2023-05-09 12:51 UTC by msarehn

Drops the requirement on boost by upping the C++ standard to C++17.

Simplifies deployment and packaging.

2023-05-15 17:04 UTC, gsauthof requested changes
Thank you for your pull-request!

Removing the boost dependency definitely makes sense now since `std::filesystem` was standardized. And just pulling it in for `to_lower_copy()` is overkill.

Thus, I'm in favor of merging your pull request.

2023-05-15 17:04 UTC, gsauthof commented on CMakeLists.txt
> +target_link_libraries(peldd)
This line can now completely be removed, right?

2023-05-15 17:04 UTC, gsauthof commented on peldd.cc
> +#include <cctype>
For which code is this header needed?

2023-05-16 07:17 UTC, msarehn commented on CMakeLists.txt
> +target_link_libraries(peldd)
Seems so. I thought that it wouldn't link at all if it wasn't present, but that seems not to be the case. Removed it.

2023-05-16 07:17 UTC, msarehn commented on peldd.cc
> +#include <cctype>
Doesn't seem to be needed at all. Removed it.

2023-05-18 11:50 UTC, gsauthof approved these changes
Excellent change!

2023-05-18 11:51 UTC, merged